services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?defina POSTGRES_DB no .env}
      POSTGRES_USER: ${POSTGRES_USER:?defina POSTGRES_USER no .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?defina POSTGRES_PASSWORD no .env}
    ports:
      - "${POSTGRES_PORT:?defina POSTGRES_PORT no .env}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:?defina POSTGRES_USER no .env} -d ${POSTGRES_DB:?defina POSTGRES_DB no .env}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
