# Generated by Django 6.1.1 on 2026-10-06 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pluggy', models.CharField(max_length=100, unique=True)),
                ('nome_banco', models.CharField(max_length=100)),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'conexão',
                'verbose_name_plural': 'conexões',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pluggy', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('corrente', 'Conta corrente'), ('cartao', 'Cartão de crédito')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('limite_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('limite_disponivel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('conexao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financas.conexao')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria_pluggy', models.CharField(blank=True, default='', max_length=100)),
                ('categoria_manual', models.CharField(blank=True, default='', max_length=100)),
                ('parcela_atual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_parcelas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id_pluggy', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financas.conta')),
            ],
            options={
                'verbose_name': 'transação',
                'verbose_name_plural': 'transações',
            },
        ),
    ]
